# Generated by Django 3.0.7 on 2021-08-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.TextField()),
                ('new_content', models.TextField()),
                ('count_word', models.IntegerField(default=0)),
                ('new_simliarity', models.IntegerField(default=0)),
            ],
        ),
    ]
